// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceScrapePrice() {
  return window['go']['gold_price_handler']['GoldPriceHandler']['ForceScrapePrice']();
}

export function GetPriceHistory(arg1) {
  return window['go']['gold_price_handler']['GoldPriceHandler']['GetPriceHistory'](arg1);
}

export function GetTodayPrice() {
  return window['go']['gold_price_handler']['GoldPriceHandler']['GetTodayPrice']();
}

export function StartPolling(arg1) {
  return window['go']['gold_price_handler']['GoldPriceHandler']['StartPolling'](arg1);
}

export function Startup(arg1) {
  return window['go']['gold_price_handler']['GoldPriceHandler']['Startup'](arg1);
}

export function UpsertTodayPrice(arg1, arg2) {
  return window['go']['gold_price_handler']['GoldPriceHandler']['UpsertTodayPrice'](arg1, arg2);
}
