// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadSmartCard() {
  return window['go']['smartcard_handler']['SmartCardHandler']['ReadSmartCard']();
}

export function Startup(arg1) {
  return window['go']['smartcard_handler']['SmartCardHandler']['Startup'](arg1);
}
