// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CeDateToBE(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['CeDateToBE'](arg1);
}

export function CreateIncomeExpense(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['CreateIncomeExpense'](arg1);
}

export function DeleteIncomeExpense(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['DeleteIncomeExpense'](arg1);
}

export function ExportIncomeExpense(arg1, arg2) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['ExportIncomeExpense'](arg1, arg2);
}

export function ExportToXlsx(arg1, arg2, arg3) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['ExportToXlsx'](arg1, arg2, arg3);
}

export function GetDailyCash(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['GetDailyCash'](arg1);
}

export function GetIncomeExpenseSummary(arg1, arg2) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['GetIncomeExpenseSummary'](arg1, arg2);
}

export function ListDailyCash(arg1, arg2) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['ListDailyCash'](arg1, arg2);
}

export function ListIncomeExpense(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['ListIncomeExpense'](arg1);
}

export function SaveDailyCash(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['SaveDailyCash'](arg1);
}

export function Startup(arg1) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['Startup'](arg1);
}

export function UpdateIncomeExpense(arg1, arg2) {
  return window['go']['income_expense_handler']['IncomeExpenseHandler']['UpdateIncomeExpense'](arg1, arg2);
}
