// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CeDateToBE(arg1:string):Promise<string>;

export function CreateIncomeExpense(arg1:models.IncomeExpenseInput):Promise<models.IncomeExpense>;

export function DeleteIncomeExpense(arg1:number):Promise<void>;

export function ExportIncomeExpense(arg1:string,arg2:string):Promise<void>;

export function ExportToXlsx(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDailyCash(arg1:string):Promise<models.DailyCash>;

export function GetIncomeExpenseSummary(arg1:string,arg2:string):Promise<models.IncomeExpenseSummary>;

export function ListDailyCash(arg1:string,arg2:string):Promise<Array<models.DailyCash>>;

export function ListIncomeExpense(arg1:models.IncomeExpenseFilter):Promise<Array<models.IncomeExpense>>;

export function SaveDailyCash(arg1:models.DailyCashInput):Promise<models.DailyCash>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateIncomeExpense(arg1:number,arg2:models.IncomeExpenseUpdateInput):Promise<void>;
