// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardStats() {
  return window['go']['dashboard_handler']['DashboardHandler']['GetDashboardStats']();
}

export function Startup(arg1) {
  return window['go']['dashboard_handler']['DashboardHandler']['Startup'](arg1);
}
