// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSale(arg1) {
  return window['go']['sale_handler']['SaleHandler']['CreateSale'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['sale_handler']['SaleHandler']['GetSetting'](arg1);
}

export function Startup(arg1) {
  return window['go']['sale_handler']['SaleHandler']['Startup'](arg1);
}
