// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllData() {
  return window['go']['settings_handler']['SettingsHandler']['ClearAllData']();
}

export function DownloadImportTemplate() {
  return window['go']['settings_handler']['SettingsHandler']['DownloadImportTemplate']();
}

export function ExportToXlsx() {
  return window['go']['settings_handler']['SettingsHandler']['ExportToXlsx']();
}

export function GetAllSettings() {
  return window['go']['settings_handler']['SettingsHandler']['GetAllSettings']();
}

export function GetBuyingDifference() {
  return window['go']['settings_handler']['SettingsHandler']['GetBuyingDifference']();
}

export function GetSettingFloat(arg1, arg2) {
  return window['go']['settings_handler']['SettingsHandler']['GetSettingFloat'](arg1, arg2);
}

export function GetSettingString(arg1, arg2) {
  return window['go']['settings_handler']['SettingsHandler']['GetSettingString'](arg1, arg2);
}

export function ImportFromXlsx() {
  return window['go']['settings_handler']['SettingsHandler']['ImportFromXlsx']();
}

export function PrintWindow() {
  return window['go']['settings_handler']['SettingsHandler']['PrintWindow']();
}

export function SaveAllSettings(arg1) {
  return window['go']['settings_handler']['SettingsHandler']['SaveAllSettings'](arg1);
}

export function SetLastTicketNumber(arg1) {
  return window['go']['settings_handler']['SettingsHandler']['SetLastTicketNumber'](arg1);
}

export function Startup(arg1) {
  return window['go']['settings_handler']['SettingsHandler']['Startup'](arg1);
}
