// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateCustomer(arg1:models.Customer):Promise<number>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function GetCustomer(arg1:number):Promise<models.Customer>;

export function GetCustomers(arg1:string):Promise<Array<models.Customer>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateCustomer(arg1:models.Customer):Promise<void>;
