// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function FindESP32Port():Promise<string>;

export function GetWiFiDisplayerIP():Promise<string>;

export function ListSerialPorts():Promise<Array<string>>;

export function ProvisionWiFi(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProvisionWiFiAuto(arg1:string,arg2:string):Promise<string>;

export function PushQR(arg1:string,arg2:handlers.Bitmap,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function PushStaticQR(arg1:string,arg2:handlers.Bitmap,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RegisterWebhook(arg1:string):Promise<void>;

export function SaveWiFiCredentials(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveWiFiCredentialsAuto(arg1:string,arg2:string):Promise<string>;

export function SendFailToDisplay():Promise<void>;

export function SendQRToDisplay(arg1:string,arg2:number):Promise<void>;

export function SendStaticQRToDisplay(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendSuccessToDisplay():Promise<void>;

export function SetShopName(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestWiFiDisplayerConnection(arg1:string):Promise<boolean>;
