// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindESP32Port() {
  return window['go']['handlers']['DisplayerHandler']['FindESP32Port']();
}

export function GetWiFiDisplayerIP() {
  return window['go']['handlers']['DisplayerHandler']['GetWiFiDisplayerIP']();
}

export function ListSerialPorts() {
  return window['go']['handlers']['DisplayerHandler']['ListSerialPorts']();
}

export function ProvisionWiFi(arg1, arg2, arg3) {
  return window['go']['handlers']['DisplayerHandler']['ProvisionWiFi'](arg1, arg2, arg3);
}

export function ProvisionWiFiAuto(arg1, arg2) {
  return window['go']['handlers']['DisplayerHandler']['ProvisionWiFiAuto'](arg1, arg2);
}

export function PushQR(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['DisplayerHandler']['PushQR'](arg1, arg2, arg3, arg4);
}

export function SaveWiFiCredentials(arg1, arg2, arg3) {
  return window['go']['handlers']['DisplayerHandler']['SaveWiFiCredentials'](arg1, arg2, arg3);
}

export function SaveWiFiCredentialsAuto(arg1, arg2) {
  return window['go']['handlers']['DisplayerHandler']['SaveWiFiCredentialsAuto'](arg1, arg2);
}

export function SendQRToDisplay(arg1, arg2) {
  return window['go']['handlers']['DisplayerHandler']['SendQRToDisplay'](arg1, arg2);
}

export function SetShopName(arg1) {
  return window['go']['handlers']['DisplayerHandler']['SetShopName'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['DisplayerHandler']['Startup'](arg1);
}

export function TestWiFiDisplayerConnection(arg1) {
  return window['go']['handlers']['DisplayerHandler']['TestWiFiDisplayerConnection'](arg1);
}
