// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateGoldItem(arg1:models.GoldItemInput):Promise<models.GoldItem>;

export function DeleteGoldItem(arg1:number):Promise<void>;

export function GetGoldItem(arg1:number):Promise<models.GoldItem>;

export function ListGoldItems(arg1:string):Promise<Array<models.GoldItem>>;

export function ListStockLogs(arg1:string):Promise<Array<models.GoldStockLog>>;

export function RecordStockLog(arg1:models.GoldStockLogInput):Promise<void>;

export function SetGoldItemStatus(arg1:number,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateGoldItem(arg1:models.GoldItemInput):Promise<void>;
