// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';
import {context} from '../models';

export function GetPriceHistory(arg1:number):Promise<Array<models.GoldPrice>>;

export function GetTodayPrice():Promise<models.GoldPrice>;

export function StartPolling(arg1:time.Duration):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
