// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['CreateGoldItem'](arg1);
}

export function DeleteGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['DeleteGoldItem'](arg1);
}

export function DeleteStockLog(arg1) {
  return window['go']['handlers']['GoldItemHandler']['DeleteStockLog'](arg1);
}

export function ExportGoldStock(arg1, arg2) {
  return window['go']['handlers']['GoldItemHandler']['ExportGoldStock'](arg1, arg2);
}

export function ExportGoldStockToXlsx(arg1, arg2, arg3) {
  return window['go']['handlers']['GoldItemHandler']['ExportGoldStockToXlsx'](arg1, arg2, arg3);
}

export function GetGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['GetGoldItem'](arg1);
}

export function GetGoldMainTypes() {
  return window['go']['handlers']['GoldItemHandler']['GetGoldMainTypes']();
}

export function GetGoldSubtypes(arg1) {
  return window['go']['handlers']['GoldItemHandler']['GetGoldSubtypes'](arg1);
}

export function GetStockLog(arg1) {
  return window['go']['handlers']['GoldItemHandler']['GetStockLog'](arg1);
}

export function ListGoldItems(arg1) {
  return window['go']['handlers']['GoldItemHandler']['ListGoldItems'](arg1);
}

export function ListStockLogs(arg1) {
  return window['go']['handlers']['GoldItemHandler']['ListStockLogs'](arg1);
}

export function RecordStockLog(arg1) {
  return window['go']['handlers']['GoldItemHandler']['RecordStockLog'](arg1);
}

export function SetGoldItemStatus(arg1, arg2) {
  return window['go']['handlers']['GoldItemHandler']['SetGoldItemStatus'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['handlers']['GoldItemHandler']['Startup'](arg1);
}

export function UpdateGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['UpdateGoldItem'](arg1);
}

export function UpdateStockLog(arg1, arg2) {
  return window['go']['handlers']['GoldItemHandler']['UpdateStockLog'](arg1, arg2);
}
