// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['CreateGoldItem'](arg1);
}

export function DeleteGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['DeleteGoldItem'](arg1);
}

export function GetGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['GetGoldItem'](arg1);
}

export function ListGoldItems(arg1) {
  return window['go']['handlers']['GoldItemHandler']['ListGoldItems'](arg1);
}

export function SetGoldItemStatus(arg1, arg2) {
  return window['go']['handlers']['GoldItemHandler']['SetGoldItemStatus'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['handlers']['GoldItemHandler']['Startup'](arg1);
}

export function UpdateGoldItem(arg1) {
  return window['go']['handlers']['GoldItemHandler']['UpdateGoldItem'](arg1);
}
