// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPriceHistory(arg1) {
  return window['go']['handlers']['GoldPriceHandler']['GetPriceHistory'](arg1);
}

export function GetTodayPrice() {
  return window['go']['handlers']['GoldPriceHandler']['GetTodayPrice']();
}

export function Startup(arg1) {
  return window['go']['handlers']['GoldPriceHandler']['Startup'](arg1);
}
