// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddPrincipalChange(arg1:models.PrincipalChangeInput):Promise<void>;

export function CreatePawn(arg1:models.PawnInput):Promise<models.PawnRecord>;

export function DeletePayment(arg1:number):Promise<void>;

export function ForfeitPawn(arg1:number):Promise<void>;

export function GetCustomerPawnRecords(arg1:number):Promise<Array<models.PawnRecord>>;

export function GetPawn(arg1:number):Promise<models.PawnRecord>;

export function GetPawnPayments(arg1:number):Promise<Array<models.PawnPayment>>;

export function GetPawnSettings():Promise<models.PawnSettings>;

export function GetPrincipalChanges(arg1:number):Promise<Array<models.PrincipalChange>>;

export function ListPawns(arg1:string,arg2:string):Promise<Array<models.PawnRecord>>;

export function RecordPayment(arg1:models.PawnPaymentInput):Promise<void>;

export function RedeemPawn(arg1:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdatePawnDescription(arg1:number,arg2:string):Promise<void>;

export function UpdatePawnInterest(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateTicketStatus(arg1:number,arg2:string):Promise<void>;
