// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPrincipalChange(arg1) {
  return window['go']['handlers']['PawnHandler']['AddPrincipalChange'](arg1);
}

export function CreatePawn(arg1) {
  return window['go']['handlers']['PawnHandler']['CreatePawn'](arg1);
}

export function DeletePayment(arg1) {
  return window['go']['handlers']['PawnHandler']['DeletePayment'](arg1);
}

export function ForfeitPawn(arg1) {
  return window['go']['handlers']['PawnHandler']['ForfeitPawn'](arg1);
}

export function GetCustomerPawnRecords(arg1) {
  return window['go']['handlers']['PawnHandler']['GetCustomerPawnRecords'](arg1);
}

export function GetPawn(arg1) {
  return window['go']['handlers']['PawnHandler']['GetPawn'](arg1);
}

export function GetPawnPayments(arg1) {
  return window['go']['handlers']['PawnHandler']['GetPawnPayments'](arg1);
}

export function GetPawnSettings() {
  return window['go']['handlers']['PawnHandler']['GetPawnSettings']();
}

export function GetPrincipalChanges(arg1) {
  return window['go']['handlers']['PawnHandler']['GetPrincipalChanges'](arg1);
}

export function ListPawns(arg1, arg2) {
  return window['go']['handlers']['PawnHandler']['ListPawns'](arg1, arg2);
}

export function RecordPayment(arg1) {
  return window['go']['handlers']['PawnHandler']['RecordPayment'](arg1);
}

export function RedeemPawn(arg1) {
  return window['go']['handlers']['PawnHandler']['RedeemPawn'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['PawnHandler']['Startup'](arg1);
}

export function UpdatePawnDescription(arg1, arg2) {
  return window['go']['handlers']['PawnHandler']['UpdatePawnDescription'](arg1, arg2);
}

export function UpdatePawnInterest(arg1, arg2, arg3) {
  return window['go']['handlers']['PawnHandler']['UpdatePawnInterest'](arg1, arg2, arg3);
}

export function UpdateTicketStatus(arg1, arg2) {
  return window['go']['handlers']['PawnHandler']['UpdateTicketStatus'](arg1, arg2);
}
