// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCustomerPurchaseRecords(arg1) {
  return window['go']['handlers']['PurchaseHandler']['GetCustomerPurchaseRecords'](arg1);
}

export function ListPurchasedGold() {
  return window['go']['handlers']['PurchaseHandler']['ListPurchasedGold']();
}

export function Startup(arg1) {
  return window['go']['handlers']['PurchaseHandler']['Startup'](arg1);
}

export function ToggleStillExists(arg1, arg2) {
  return window['go']['handlers']['PurchaseHandler']['ToggleStillExists'](arg1, arg2);
}

export function UpdateNotes(arg1, arg2) {
  return window['go']['handlers']['PurchaseHandler']['UpdateNotes'](arg1, arg2);
}
