// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateSale(arg1:models.SaleInput):Promise<models.Sale>;

export function GetSetting(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
