// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIncomeExpense(arg1, arg2) {
  return window['go']['handlers']['SaleHandler']['CreateIncomeExpense'](arg1, arg2);
}

export function CreateSale(arg1) {
  return window['go']['handlers']['SaleHandler']['CreateSale'](arg1);
}

export function DeleteIncomeExpense(arg1, arg2) {
  return window['go']['handlers']['SaleHandler']['DeleteIncomeExpense'](arg1, arg2);
}

export function ExportIncomeExpense(arg1, arg2) {
  return window['go']['handlers']['SaleHandler']['ExportIncomeExpense'](arg1, arg2);
}

export function ExportToXlsx(arg1, arg2, arg3) {
  return window['go']['handlers']['SaleHandler']['ExportToXlsx'](arg1, arg2, arg3);
}

export function GetIncomeExpenseSummary(arg1, arg2, arg3) {
  return window['go']['handlers']['SaleHandler']['GetIncomeExpenseSummary'](arg1, arg2, arg3);
}

export function GetSetting(arg1) {
  return window['go']['handlers']['SaleHandler']['GetSetting'](arg1);
}

export function ListIncomeExpense(arg1, arg2) {
  return window['go']['handlers']['SaleHandler']['ListIncomeExpense'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['handlers']['SaleHandler']['Startup'](arg1);
}
