// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';
import {models} from '../models';
import {context} from '../models';

export function CreateIncomeExpense(arg1:sql.DB,arg2:models.IncomeExpenseInput):Promise<models.IncomeExpense>;

export function CreateSale(arg1:models.SaleInput):Promise<models.Sale>;

export function DeleteIncomeExpense(arg1:sql.DB,arg2:number):Promise<void>;

export function ExportIncomeExpense(arg1:string,arg2:string):Promise<void>;

export function ExportToXlsx(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetIncomeExpenseSummary(arg1:sql.DB,arg2:string,arg3:string):Promise<models.IncomeExpenseSummary>;

export function GetSale(arg1:number):Promise<models.Sale>;

export function ListIncomeExpense(arg1:sql.DB,arg2:models.IncomeExpenseFilter):Promise<Array<models.IncomeExpense>>;

export function ListSales(arg1:string):Promise<Array<models.Sale>>;

export function Startup(arg1:context.Context):Promise<void>;
