// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAllSettings():Promise<Record<string, string>>;

export function GetSettingFloat(arg1:string,arg2:number):Promise<number>;

export function GetSettingString(arg1:string,arg2:string):Promise<string>;

export function PrintWindow():Promise<void>;

export function SaveAllSettings(arg1:Record<string, string>):Promise<void>;

export function SetLastTicketNumber(arg1:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
