// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadImportTemplate() {
  return window['go']['handlers']['SettingsHandler']['DownloadImportTemplate']();
}

export function GetAllSettings() {
  return window['go']['handlers']['SettingsHandler']['GetAllSettings']();
}

export function GetBuyingDifference() {
  return window['go']['handlers']['SettingsHandler']['GetBuyingDifference']();
}

export function GetSettingFloat(arg1, arg2) {
  return window['go']['handlers']['SettingsHandler']['GetSettingFloat'](arg1, arg2);
}

export function GetSettingString(arg1, arg2) {
  return window['go']['handlers']['SettingsHandler']['GetSettingString'](arg1, arg2);
}

export function ImportFromXlsx() {
  return window['go']['handlers']['SettingsHandler']['ImportFromXlsx']();
}

export function PrintWindow() {
  return window['go']['handlers']['SettingsHandler']['PrintWindow']();
}

export function SaveAllSettings(arg1) {
  return window['go']['handlers']['SettingsHandler']['SaveAllSettings'](arg1);
}

export function SetLastTicketNumber(arg1) {
  return window['go']['handlers']['SettingsHandler']['SetLastTicketNumber'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['SettingsHandler']['Startup'](arg1);
}
