// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSettings() {
  return window['go']['handlers']['SettingsHandler']['GetAllSettings']();
}

export function GetSettingFloat(arg1, arg2) {
  return window['go']['handlers']['SettingsHandler']['GetSettingFloat'](arg1, arg2);
}

export function GetSettingString(arg1, arg2) {
  return window['go']['handlers']['SettingsHandler']['GetSettingString'](arg1, arg2);
}

export function SaveAllSettings(arg1) {
  return window['go']['handlers']['SettingsHandler']['SaveAllSettings'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['SettingsHandler']['Startup'](arg1);
}
