// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CastToInventory(arg1, arg2) {
  return window['go']['purchase_handler']['PurchaseHandler']['CastToInventory'](arg1, arg2);
}

export function GetCustomerPurchaseRecords(arg1) {
  return window['go']['purchase_handler']['PurchaseHandler']['GetCustomerPurchaseRecords'](arg1);
}

export function ListPurchasedGold() {
  return window['go']['purchase_handler']['PurchaseHandler']['ListPurchasedGold']();
}

export function Startup(arg1) {
  return window['go']['purchase_handler']['PurchaseHandler']['Startup'](arg1);
}

export function ToggleIsInventory(arg1, arg2) {
  return window['go']['purchase_handler']['PurchaseHandler']['ToggleIsInventory'](arg1, arg2);
}

export function ToggleStillExists(arg1, arg2) {
  return window['go']['purchase_handler']['PurchaseHandler']['ToggleStillExists'](arg1, arg2);
}

export function UpdateNotes(arg1, arg2) {
  return window['go']['purchase_handler']['PurchaseHandler']['UpdateNotes'](arg1, arg2);
}
