// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CastToInventory(arg1:number,arg2:number):Promise<void>;

export function GetCustomerPurchaseRecords(arg1:number):Promise<Array<models.PurchasedGold>>;

export function ListPurchasedGold():Promise<Array<models.PurchasedGold>>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleIsInventory(arg1:number,arg2:number):Promise<void>;

export function ToggleStillExists(arg1:number,arg2:number):Promise<void>;

export function UpdateNotes(arg1:number,arg2:string):Promise<void>;
