// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['customer_handler']['CustomerHandler']['CreateCustomer'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['customer_handler']['CustomerHandler']['DeleteCustomer'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['customer_handler']['CustomerHandler']['GetCustomer'](arg1);
}

export function GetCustomers(arg1) {
  return window['go']['customer_handler']['CustomerHandler']['GetCustomers'](arg1);
}

export function Startup(arg1) {
  return window['go']['customer_handler']['CustomerHandler']['Startup'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['customer_handler']['CustomerHandler']['UpdateCustomer'](arg1);
}
