// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateCustomer(arg1:db.Customer):Promise<number>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function GetCustomer(arg1:number):Promise<db.Customer>;

export function GetCustomerPawnRecords(arg1:number):Promise<Array<db.PawnRecord>>;

export function GetCustomers(arg1:string):Promise<Array<db.Customer>>;

export function Greet(arg1:string):Promise<string>;

export function ReadSmartCard():Promise<db.Customer>;

export function UpdateCustomer(arg1:db.Customer):Promise<void>;
