// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['main']['App']['GetCustomer'](arg1);
}

export function GetCustomerPawnRecords(arg1) {
  return window['go']['main']['App']['GetCustomerPawnRecords'](arg1);
}

export function GetCustomers(arg1) {
  return window['go']['main']['App']['GetCustomers'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadSmartCard() {
  return window['go']['main']['App']['ReadSmartCard']();
}

export function UpdateCustomer(arg1) {
  return window['go']['main']['App']['UpdateCustomer'](arg1);
}
