// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWiFiDisplayerIP():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListSerialPorts():Promise<Array<string>>;

export function SaveWiFiCredentials(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveWiFiCredentialsAuto(arg1:string,arg2:string):Promise<string>;

export function SendQRToDisplay(arg1:string):Promise<void>;

export function TestWiFiDisplayerConnection(arg1:string):Promise<boolean>;
