// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWiFiDisplayerIP() {
  return window['go']['main']['App']['GetWiFiDisplayerIP']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function SaveWiFiCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWiFiCredentials'](arg1, arg2, arg3);
}

export function SaveWiFiCredentialsAuto(arg1, arg2) {
  return window['go']['main']['App']['SaveWiFiCredentialsAuto'](arg1, arg2);
}

export function SendQRToDisplay(arg1) {
  return window['go']['main']['App']['SendQRToDisplay'](arg1);
}

export function TestWiFiDisplayerConnection(arg1) {
  return window['go']['main']['App']['TestWiFiDisplayerConnection'](arg1);
}
