// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPhysicalConnection() {
  return window['go']['displayer_handler']['DisplayerHandler']['CheckPhysicalConnection']();
}

export function FindESP32Port() {
  return window['go']['displayer_handler']['DisplayerHandler']['FindESP32Port']();
}

export function GetWiFiDisplayerIP() {
  return window['go']['displayer_handler']['DisplayerHandler']['GetWiFiDisplayerIP']();
}

export function ListSerialPorts() {
  return window['go']['displayer_handler']['DisplayerHandler']['ListSerialPorts']();
}

export function ProvisionWiFi(arg1, arg2, arg3) {
  return window['go']['displayer_handler']['DisplayerHandler']['ProvisionWiFi'](arg1, arg2, arg3);
}

export function ProvisionWiFiAuto(arg1, arg2) {
  return window['go']['displayer_handler']['DisplayerHandler']['ProvisionWiFiAuto'](arg1, arg2);
}

export function PushQR(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['displayer_handler']['DisplayerHandler']['PushQR'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PushStaticQR(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['displayer_handler']['DisplayerHandler']['PushStaticQR'](arg1, arg2, arg3, arg4, arg5);
}

export function RegisterWebhook(arg1) {
  return window['go']['displayer_handler']['DisplayerHandler']['RegisterWebhook'](arg1);
}

export function SaveWiFiCredentials(arg1, arg2, arg3) {
  return window['go']['displayer_handler']['DisplayerHandler']['SaveWiFiCredentials'](arg1, arg2, arg3);
}

export function SaveWiFiCredentialsAuto(arg1, arg2) {
  return window['go']['displayer_handler']['DisplayerHandler']['SaveWiFiCredentialsAuto'](arg1, arg2);
}

export function SendFailToDisplay() {
  return window['go']['displayer_handler']['DisplayerHandler']['SendFailToDisplay']();
}

export function SendQRToDisplay(arg1, arg2) {
  return window['go']['displayer_handler']['DisplayerHandler']['SendQRToDisplay'](arg1, arg2);
}

export function SendStaticQRToDisplay(arg1, arg2, arg3, arg4) {
  return window['go']['displayer_handler']['DisplayerHandler']['SendStaticQRToDisplay'](arg1, arg2, arg3, arg4);
}

export function SendSuccessToDisplay() {
  return window['go']['displayer_handler']['DisplayerHandler']['SendSuccessToDisplay']();
}

export function SetShopName(arg1) {
  return window['go']['displayer_handler']['DisplayerHandler']['SetShopName'](arg1);
}

export function Startup(arg1) {
  return window['go']['displayer_handler']['DisplayerHandler']['Startup'](arg1);
}

export function TestWiFiDisplayerConnection(arg1) {
  return window['go']['displayer_handler']['DisplayerHandler']['TestWiFiDisplayerConnection'](arg1);
}
